### ISSUE TITLE
doc isn't finished....

### ISSUE THREAD

**Issue by Phouter0499** [shner-elmo/flashtext2#4]
why did you not document kp.extract_keywords_with_span method in flashtext2????
i had to look for it and i found it in [flashtext2.pyi](https://github.com/shner-elmo/flashtext2/blob/master/flashtext2.pyi)
it does seeem to be working....anyways you should add to your doc about extract_keywords_with_span method...

**Comment by shner-elmo** [comment]
@Phouter0499 send pr

**Comment by Phouter0499** [comment]
```python
from flashtext2 import KeywordProcessor

kp = KeywordProcessor(case_sensitive=True)
text = "The Teloschistaceae are a large family of mostly lichen-forming fungi belonging to the class Lecanoromycetes in the division Ascomycota."
kp.add_keyword("Teloschistaceae", "**Teloschistaceae**")
kp.add_keyword("Lecanoromycetes")
ekw_list = kp.extract_keywords_with_span(text)
print(ekw_list) # [('**Teloschistaceae**', 4, 19), ('Lecanoromycetes', 93, 108)]
```

**Comment by shner-elmo** [comment]
Yeah that's not a pull request

**Comment by Phouter0499** [comment]
lol sorry about that i thought you meant program. anyways i made the pull request pls review.

**Comment by shner-elmo** [comment]
Finally it feels like talking to a normal person 😅

**Comment by shner-elmo** [comment]
I merged the PR
