### ISSUE TITLE
case-insensitive is not currently supported

### ISSUE THREAD

**Issue by lucazav** [shner-elmo/flashtext2#7]
I found that `KeywordProcessor(case_sensitive=False)` is not supported yet.

Any ETA to support it?

Thank you.

**Comment by shner-elmo** [comment]
Hey Luca, I added case-insensitive support to the underlying rust crate recently.
So now it is possible to add it here, just have to update `src/lib.rs`. 

> Any ETA to support it?

Probably within 2-3 weeks

**Comment by lucazav** [comment]
Great news! If you don't mind, just link the release here to close the issue when it will be ready. Thank you!

**Comment by shner-elmo** [comment]
You got it man

**Comment by shner-elmo** [comment]
@lucazav Just released version `1.1.0` on PyPI
